name: api_test_pipeline

on:
 workflow_dispatch:
 schedule:
  - cron: 00 15 * * 1-5

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Pull postman collections
        uses: actions/checkout@v3
        with:
          ref: main

      # Runs a single command using the runners shell
      - name: Install newman
        run: |
         npm install -g newman
         npm install -g newman-reporter-htmlextra

      # Runs a set of commands using the runners shell
      - name: Run postman collections
        run: newman run 'Trello_Daniil_DZ.postman_collection_no_auth.json -e Trello_UAT.postman_environment.json'
      
        
          
        
